object_geometries:
  box       : {box: [0.15, 0.15, 0.45], color: [0.75,0.75,0.75,1]}
  little_box: {box: [0.1, 0.1, 0.1]   , color: [1,0.0,0.0,1]     }
  big_box   : {box: [0.4, 0.4, 0.6]   , color: [0.75,0.75,0.75,1]}
  huge_box  : {box: [0.8, 0.8, 1.5]   , color: [0.75,0.75,0.75,1]}
