#TEST CONFIGURATIONS:
n_query: 50
n_iter_per_query: 10

#PLANNING CONFIGURATIONS:
group_name: "uav_arm"
start_configuration: [0.0,0.0,0.0]
stop_configuration:  [10,10,2]
utopia_tolerance: 0.05
extend: false
max_distance: 0.5
checker_resolution: 0.05
parallel_checker_n_threads: 20

#REPLANNER CONFIGURATIONS:

# Available replanners:
# - MPRRT
# - DRRT*
# - DRRT
# - anytimeDRRT
# - MARS

replanner_type: "MARS"
dt_replan: 0.20
trj_execution_thread_frequency: 500
collision_checker_thread_frequency: 30
benchmark: true
spawn_objs: true
spawn_instants: [1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49]
obj_type: "box"
obj_max_size: 0.1
scaling: 0.5
read_safe_scaling: false
read_real_joints_values_: false

MPRRT:
  n_threads_replan: 5

MARS:
  n_other_paths: 3
  reverse_start_nodes: true
  full_net_search: false
  dt_replan_relaxed: 0.20
  verbosity_level: 2

#VERBOSITY:
replanner_verbosity: false
display_timing_warning: true
display_replanning_success: true
display_replan_trj_point: true
display_replan_config: true
display_current_trj_point: true
display_current_config: true
