#TEST CONFIGURATIONS:
n_iter: 500

#PLANNING CONFIGURATIONS:
group_name: "cartesian_arm"
start_configuration: [0.2,0.2,0.2]
stop_configuration:  [0.8,0.8,0.8]
utopia_tolerance: 0.05
extend: false
max_distance: 0.3
checker_resolution: 0.01

#REPLANNER CONFIGURATIONS:

# Available replanners:
# - MPRRT
# - DRRT*
# - DRRT
# - anytimeDRRT
# - AIPRO

replanner_type: "AIPRO"
dt_replan: 0.20
trj_execution_thread_frequency: 500
collision_checker_thread_frequency: 30
spawn_objs: true
spawn_instants: [0.8, 1.6, 2.4]
obj_type: "scatola"
scaling: 0.5
read_safe_scaling: false
read_real_joints_values_: false

to_goal:
  n_threads_replan: 5

aipro:
  n_other_paths: 3
  dt_replan_relaxed: 0.20
  verbosity_level: 1

#VERBOSITY:
replanner_verbosity: true
display_timing_warning: true
display_replanning_success: true
display_replan_trj_point: true
display_replan_config: true
display_current_trj_point: true
display_current_config: true
