# Replanner strategy:
# - MPRRT
# - DRRT*
# - DRRT
# - anytimeDRRT
# - AIPRO

replanner_type: "AIPRO"
group_name: "cartesian_arm"
start_configuration: [0.2,0.2,0.2]
stop_configuration:  [0.8,0.8,0.8]
max_distance: 0.5
extend: false
utopia_tolerance: 0.05
dt_replan: 0.2
n_iter: 500
display: false
rj_execution_thread_frequency: 500
collision_checker_thread_frequency: 30
spawn_objs: true
display_timing_warning: true
display_replanning_success: true
scaling: 0.5
read_real_joints_values_: false
checker_resolution: 0.01
replanner_verbosity: true

to_goal:
  n_threads_replan: 5

aipro:
  n_other_paths: 2
  dt_replan_replaxed: 0.21
  verbosity_level: 0
