#TEST CONFIGURATIONS:
n_query: 50
n_iter_per_query: 10

#PLANNING CONFIGURATIONS:
group_name: "cartesian_arm"
start_configuration: [0.2,0.2,0.2]
stop_configuration:  [0.8,0.8,0.8]
utopia_tolerance: 0.05
extend: false
max_distance: 0.1
checker_resolution: 0.01
parallel_checker_n_threads: 4

#REPLANNER CONFIGURATIONS:

# Available replanners:
# - MPRRT
# - DRRT*
# - DRRT
# - anytimeDRRT
# - MARS
# - MARSHA

replanner_type: "MARSHA"
dt_replan: 0.20
trj_execution_thread_frequency: 500
collision_checker_thread_frequency: 30
benchmark: true
spawn_objs: true
spawn_instants: [0.5, 2]
obj_type: "little_box"
obj_max_size: 0.05
scaling: 0.5
read_safe_scaling: false
read_real_joints_values_: false

MPRRT:
  n_threads_replan: 5

MARS:
  n_other_paths: 3
  reverse_start_nodes: true
  full_net_search: false
  dt_replan_relaxed: 0.20
  verbosity_level: 1

MARSHA:
  base_frame: "link_X"
  tool_frame: "end_effector"
  ssm_max_step_size: 0.05
  ssm_threads: 4
  unaware_obstacles: ["manipulation/box/n_0","manipulation/box/n_1"]
  poi_names: ["end_effector"]
  max_cart_acc: 2.5
  Tr: 0.15
  min_distance: 0.8
  v_h: 1.6

#VERBOSITY:
display: false
replanner_verbosity: true
display_timing_warning: false
display_replanning_success: true
display_replan_trj_point: false
display_replan_config: true
display_current_trj_point: true
display_current_config: true
