# Available replanners:
# - MPRRT
# - DRRT*
# - DRRT
# - anytimeDRRT
# - AIPRO

replanner_type: "DRRT*"
group_name: "cartesian_arm"
start_configuration: [0.2,0.2,0.2]
stop_configuration:  [0.8,0.8,0.8]
max_distance: 0.2
extend: false
utopia_tolerance: 0.05
max_time: 0.2
n_iter: 500
display: false

to_goal:
  n_threads_replan: 5

aipro:
  n_other_paths: 2
  reverse_start_nodes: true
