# Replanner strategy:
# - MPRRT
# - DRRT*
# - DRRT
# - anytimeDRRT
# - MARS

replanner_type: "DRRT*"
group_name: "cartesian_arm"
max_time: 0.2
start_configuration: [0.2, 0.2, 0.2]
stop_configuration: [2.8, 2.8, 2.8]
n_iter: 3
max_distance: 0.2

display: true
verbose: true

MPRRT:
  n_threads_replan: 5

MARS:
  n_other_paths: 1
  verbose: true
  display: true
