# Replanner strategy:
# - replanner_to_goal
# - DRRT*
# - DRRT

replanner_type: "DRRT"
group_name: "cartesian_arm"
base_link: "world"
last_link: "end_effector"
max_time: 1000000000
start_configuration: [0.2, 0.2, 0.2]
stop_configuration: [0.8, 0.8, 0.8]
