# Replanner strategy:
# - replanner_to_goal
# - DRRT*
# - DRRT
# - anytimeDRRT

replanner_type: "anytimeDRRT"
group_name: "cartesian_arm"
base_link: "world"
last_link: "end_effector"
max_time: 0.2
start_configuration: [0.2, 0.2, 0.2]
stop_configuration: [0.8, 0.8, 0.8]
n_iter: 3

to_goal:
  n_threads_replan: 5
