# Replanner strategy:
# - MPRRT
# - DRRT*
# - DRRT
# - anytimeDRRT

replanner_type: "anytimeDRRT"
group_name: "cartesian_arm"
start_configuration: [0.2, 0.2, 0.2]
stop_configuration: [2.8, 2.8, 2.8]
dt_replan: 0.2
trj_execution_thread_frequency: 500
collision_checker_thread_frequency: 30
spawn_objs: true
display_timing_warning: true
display_replanning_success: true
scaling: 0.5
read_real_joints_values_: false
checker_resolution: 0.03
parallel_checker_n_threads: 20
max_distance: 0.2

MPRRT:
  n_threads_replan: 5
