# Replanner strategy:
# - replanner_to_goal
# - DRRT*
# - DRRT
# - anytimeDRRT
# - AIPRO

replanner_type: "AIPRO"
group_name: "cartesian_arm"
max_time: 0.2
start_configuration: [0.2, 0.2, 0.2]
stop_configuration: [0.8, 0.8, 0.8]
n_iter: 3

to_goal:
  n_threads_replan: 5

aipro:
  n_other_paths: 2
  verbose: true
  display: true
