object_geometries:
  box       : {box: [0.2, 0.2, 0.45], color: [0.75,0.75,0.75,1]}
  little_box: {box: [0.1, 0.1, 0.1 ], color: [0.75,0.75,0.75,1]}
  mid_box   : {box: [0.4, 0.4, 0.5 ], color: [0.75,0.75,0.75,1]}
  short_box : {box: [0.5, 0.5, 0.5 ], color: [0.75,0.75,0.75,1]}
  big_box   : {box: [0.5, 0.5,   3 ], color: [0.75,0.75,0.75,1]}
  huge_box  : {box: [0.8, 0.8,   3 ], color: [0.75,0.75,0.75,1]}
  plane     : {box: [5,     5, 0.1 ], color: [0.75,0.75,0.75,1]}
