scene_objects:
 - {type: "box",      frame: "world", position: [0.5,0.5,0.5],  quaternion: [0, 0, 0, 1]}
 - {type: "box",      frame: "world", position: [1,4,0.7],      quaternion: [0, 0, 0, 1]}
 - {type: "box",      frame: "world", position: [3.5,3.5,1],    quaternion: [0, 0, 0, 1]}
 - {type: "box",      frame: "world", position: [4,1,0.7],      quaternion: [0, 0, 0, 1]}
 - {type: "huge_box", frame: "world", position: [2,2,0.5],      quaternion: [0, 0, 0, 1]}
 - {type: "huge_box", frame: "world", position: [2.5,5.5,0.5],  quaternion: [0, 0, 0, 1]}
 - {type: "huge_box", frame: "world", position: [5.5,4,0.5],    quaternion: [0, 0, 0, 1]}
 - {type: "huge_box", frame: "world", position: [6,2,0.5],      quaternion: [0, 0, 0, 1]}
