#TEST CONFIGURATIONS:
n_query: 20
n_iter_per_query: 10
bench_name: "12d"

#PLANNING CONFIGURATIONS:
group_name: "manipulator"
start_configuration: [1.377, 0.291, -0.327, -0.152, 0.723, 1.504, -0.327, -1.1038, -1.1039, -0.06067, -0.0789, 0.2304]
end_start_configuration: [1.376, 0.299, -1.57, -0.133, 0.279, 0.928, 0.109, -1.1002, 0.424, 0.291, 0.3456, 0.221]
stop_configuration: [-1.159, -0.8949, 1.385, -0.3501, -0.9964, -1.3500, -0.0225, 0.8918, 0.1913, 0.041, -0.215, 1.516]
end_stop_configuration: [-1.4415, 0.5835, 0.8058, -0.0984, -0.4665, -0.487, 0.5335, 0.277, 0.0182, -0.152, -0.5413, 0.3429]

utopia_tolerance: 0.05
extend: false
max_distance: 0.3
checker_resolution: 0.05
parallel_checker_n_threads: 20
max_solver_time: 30

#REPLANNER CONFIGURATIONS:

# Available replanners:
# - MPRRT
# - DRRTStar
# - DRRT
# - anytimeDRRT
# - MARS

replanner_type_vector: ["MARS","DRRTStar","DRRT","anytimeDRRT","MPRRT"]
dt_replan: 0.20
trj_execution_thread_frequency: 500
collision_checker_thread_frequency: 30
benchmark: true
spawn_objs: true
spawn_instants: [0.5,2.5,4.5]
obj_type: "red_box"
obj_max_size: 0.1
scaling: 1
read_safe_scaling: false

MPRRT:
  n_threads_replan: 5

MARS:
  n_other_paths: 2
  reverse_start_nodes: true
  full_net_search: false
  dt_replan_relaxed: 0.20
  verbosity_level: 2

#VERBOSITY:
replanner_verbosity: true
display_timing_warning: false
display_replanning_success: true
display_replan_trj_point: false
display_replan_config: false
display_current_trj_point: false
display_current_config: false
