#TEST CONFIGURATIONS:
n_query: 20
n_iter_per_query: 10
bench_name: "3d_simple"

#PLANNING CONFIGURATIONS:
group_name: "cartesian_arm"
start_configuration: [0,0,0]
end_start_configuration: [0,3,2]
stop_configuration:  [3,3,2]
end_stop_configuration:  [3,0,0]
utopia_tolerance: 0.05
extend: false
max_distance: 0.3
checker_resolution: 0.05
parallel_checker_n_threads: 20

#REPLANNER CONFIGURATIONS:

# Available replanners:
# - MPRRT
# - DRRTStar
# - DRRT
# - anytimeDRRT
# - MARS

replanner_type_vector: ["DRRT","anytimeDRRT","MPRRT"]   #["MARS","DRRTStar","DRRT","anytimeDRRT","MPRRT"]
dt_replan: 0.20
trj_execution_thread_frequency: 500
collision_checker_thread_frequency: 30
benchmark: true
spawn_objs: true
spawn_instants: [0.5,3.5,6.5]
obj_type: "red_box"
obj_max_size: 0.1
scaling: 0.7
read_safe_scaling: false

MPRRT:
  n_threads_replan: 5

MARS:
  n_other_paths: 2
  reverse_start_nodes: true
  full_net_search: false
  dt_replan_relaxed: 0.20
  verbosity_level: 2

#VERBOSITY:
replanner_verbosity: true
display_timing_warning: false
display_replanning_success: true
display_replan_trj_point: true
display_replan_config: true
display_current_trj_point: true
display_current_config: true
