#PLANNING CONFIGURATIONS:
group_name: "cartesian_arm"
start_configuration: [0,0,0]
end_start_configuration: [0,3,2]
stop_configuration:  [3,3,2]
end_stop_configuration:  [3,0,0]
max_distance: 0.3 #max connections length
checker_resolution: 0.05
parallel_checker_n_threads: 20

#REPLANNING CONFIGURATIONS:
dt_replan: 0.20
trj_execution_thread_frequency: 500
collision_checker_thread_frequency: 30
spawn_objs: true  #to start a thread that will generate random objects on the current path
spawn_instants: [0.5,3.5,6.5] #instants of time in which to generate random objects
obj_type: "red_box" #object to generate (see object_test_replanner.yaml in replanners_bench_cell to see a list of available objects)
scaling: 0.7  #scaling factor of robot trajectory (value between 0 and 1)

replanner_verbosity: true
display_timing_warning: false
display_replanning_success: true
display_replan_trj_point: false #show starting point for replanning on trajectory
display_replan_config: false #show projection of starting point of replanning on current path
display_current_trj_point: true #show robot end effector position on trajectory
display_current_config: false #show projection of robot position on current path
